name: mlflow-project

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow==2.19.0
      - xgboost==2.1.3
      - numpy==2.0.2
      - scikit-learn==1.5.2